### ISSUE TITLE
Support tagging.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [FossifyOrg/Notes#23] opened 2024-02-23 17:10 UTC
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/FossifyOrg/Notes/issues) or [closed](https://github.com/FossifyOrg/Notes/issues?q=is%3Aissue+is%3Aclosed) - to which I could contribute my information.
- [X] I made sure that there are **no existing discussions** - [open](https://github.com/FossifyOrg/Notes/discussions) or [closed](https://github.com/FossifyOrg/Notes/discussions?discussions_q=is%3Aclosed) - to which I could contribute my information.
- [X] I have read the FAQs inside the app (Menu -> About -> FAQs) and my problem isn't listed.
- [X] **I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.**
- [X] This issue contains only one feature request.
- [X] I have read and understood the [contribution guidelines](https://github.com/FossifyOrg/Notes/blob/master/CONTRIBUTING.md).
- [ ] I optionally [donated](https://fossify.org/donate) to support the Fossify mission.

### Feature description

A one-to-many correspondence, possible to combine and exclude when filtering.

### Why do you want this feature?

To organize them in a manner which embeds into the text file which the note content is stored in, or via the file system as https://github.com/FossifyOrg/File-Manager/issues/60#issue-2151476679 requests, but via the Notes GUI for the sake of accessibility to the technically less competent, and convenience for all, regardless of competence.

### Additional information

https://github.com/FossifyOrg/General-Discussion/issues/127#issuecomment-1958772679

**Comment by Aga-C** [comment] 2024-02-23 17:15
It's a duplicate of https://github.com/FossifyOrg/Notes/issues/18.

**Closed by Aga-C** 2024-02-23 17:15 UTC
Labels: feature request, needs triage
